# Generated by Django 2.2.6 on 2019-10-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('course_link', models.URLField()),
                ('course_type', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=10)),
                ('Medium', models.CharField(choices=[('Video', 'Video'), ('Documents', 'Documents')], max_length=20)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_link', models.URLField()),
                ('provider_logo', models.ImageField(upload_to='provider_logos')),
            ],
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_source', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivist_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='logos')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivist_app.Domains')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivist_app.Domains'),
        ),
        migrations.AddField(
            model_name='course',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivist_app.Keywords'),
        ),
        migrations.AddField(
            model_name='course',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivist_app.Course_Provider'),
        ),
    ]
