# Generated by Django 2.2.6 on 2019-10-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivist_app', '0002_course_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_provider',
            name='provider_logo',
            field=models.ImageField(upload_to='provider_logos'),
        ),
    ]
